[project]
name = "seminar-2025-09-03"
version = "0.1.0"
description = "Auburn Graduate Students Seminar slides and Manim assets"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "manim>=0.19",
]

[tool.uv]
dev-dependencies = [
  "numpy>=1.24",
]

